---
title: "Assembly"
output: html_document
date: "2024-06-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Preprocessing

##Loading Color Pallettes

```{r}
# color blind pallets used throughout 
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
ibm.cbb <- c("#648FFF", "#785EF0", "#DC267F", "#FE6100", "#FFB000")
tol.cbb <- c("#332288", "#117733", "#44AA99", "#88CCEE", "#DDCC77", "#CC6677", "#AA4499", "#882255")
```

##Loading Libraries

```{r}
#Installing Packages
#install.packages("file2meco")
#install.packages("microeco")
#install.packages("GUniFrac")
install.packages("ggtern")
#Loading Libraries
library(file2meco)
library(microeco)
library(phyloseq)
library(microbiome)
library(vegan)
library(tidyverse)
library(ggplot2)
library(minpack.lm)
library(Hmisc)
library(stats4)
library(ggrepel)
library(ggpubr)
library(dplyr)
library(GUniFrac)


```

#Loading in RDS

```{r}
bac_sperm <- readRDS("Bacteria_RDS/Spermosphere_bac_clean.rds")

TaxaTable <- as.data.frame(bac_sperm@tax_table)
```

```{r}
library(microeco)
library(file2meco)

bac_sperm_filt <- bac_sperm_filt %>%
    subset_samples(Sample_Type == "Spermosphere")

bac_sperm_filt@sam_data$LocationTime <- paste(bac_sperm_filt@sam_data$Location_EC, bac_sperm_filt@sam_data$Time, sep = "-")

 microeco_bac_sperm <- phyloseq2meco(bac_sperm_filt) 

 test <- clone(microeco_bac_sperm)

test$cal_betadiv()
test$cal_alphadiv()

# generate trans_nullmodel object
# as an example, we only use high abundance OTU with mean relative abundance > 0.0005
t1 <- trans_nullmodel$new(test, filter_thres = 0.0005, add_data = bac_sperm_filt@sam_data)

str(t1)

t1$cal_mantel_corr(use_env = "LocationTime")
t1$plot_mantel_corr()

# see null.model parameter for other null models
# null model run 500 times for the example
t1$cal_ses_betampd(runs = 500, abundance.weighted = TRUE)
# return t1$res_ses_betampd
# add betaNRI matrix to beta_diversity list
test$beta_diversity[["betaNRI"]] <- t1$res_ses_betampd
# create trans_beta class, use measure "betaNRI"
t2 <- trans_beta$new(dataset = test, group = "LocationTime", measure = "betaNRI")
# transform the distance for each group
t2$cal_group_distance()
# see the help document for more methods, e.g. "anova" and "KW_dunn"
library(agricolae)
t2$cal_group_distance_diff(method = "anova")

# plot the results
g1 <- t2$plot_group_distance(add = "mean")
g1 + geom_hline(yintercept = -2, linetype = 2) + geom_hline(yintercept = 2, linetype = 2)


library(tidyverse)

Resgroup <- t2$res_group_distance

Resgroup2 <- Resgroup %>%
  separate(LocationTime, into = c("Location", "Time"), sep = "-")
  
Resgroup2$Time<- factor(Resgroup2$Time, levels = c("0", "8", "12", "16"))

 BetaNRIplot <- Resgroup2 %>%
  ggplot(aes(x = Time, y = Value, color = Location)) +
  #facet_wrap(~factor(Time, levels = c("Planting", "17hrs", "V2")), scale = "free") +
  geom_boxplot(position = position_dodge2(0.85, preserve = "single")) + 
  geom_point(position=position_jitterdodge(0.05)) +
  #geom_pwc(aes(group = Trt), method = "t_test", label = "p.adj.format") +
  #stat_compare_means(method = "t.test") +
  scale_y_continuous(limits = c(-4, 4), breaks = seq(-4, 4), 0.5) +
  scale_fill_manual(values = cbbPalette ) +
  color_palette(cbbPalette) +
  #stat_summary(fun = mean,geom="line") +
  #stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.5) +
  ylab("betaNRI") +
  xlab("Type of Environment")+
  #geom_jitter(width = 0.1, alpha = 0.8)+
  #scale_color_manual(values=cbbPalette, name = "", labels = c("Planting", "17hrs", "V2")) +  
  #stat_compare_means(method = "kruskal", hide.ns = TRUE) +
  theme_classic()+
  theme(legend.text = element_text(face = "italic", size = 12), legend.title = element_blank())
 
sessionInfo() 

BetaNRIplot <- Resgroup2 %>%
  ggplot(aes(x = Time, y = Value, color = Location)) +
  geom_boxplot(position = position_dodge2(0.85, preserve = "single")) + 
  geom_point(position = position_jitterdodge(0.05)) +
  geom_hline(yintercept = 2, linetype = "dashed", color = "black") +
  geom_hline(yintercept = -2, linetype = "dashed", color = "black") +
  scale_y_continuous(limits = c(-4, 4), breaks = seq(-4, 4, 0.5)) +
  scale_fill_manual(values = cbbPalette) +
  color_palette(cbbPalette) +
  ylab("betaNRI") +
  xlab("Type of Environment") +
  theme_classic() +
  theme(legend.text = element_text(face = "italic", size = 12), legend.title = element_blank())


                
# null model run 500 times
t1$cal_ses_betamntd(runs = 500, abundance.weighted = TRUE, null.model = "taxa.labels")
# return t1$res_ses_betamntd

# result stored in t1$res_rcbray
t1$cal_rcbray(runs = 1000)
# return t1$res_rcbray

# use betaNTI and rcbray to evaluate processes
t1$cal_process(use_betamntd = TRUE, group = "TrtTypeTime")
TRTYPETIME <- t1$res_process
t1$cal_process(use_betamntd = TRUE, group = "TrtType")
TRTYPE <- t1$res_process

t1$cal_process(use_betamntd = TRUE)

# require NST package to be installed
install.packages("NST")
library(NST)

t1$cal_NST(method = "tNST", group = "TrtTypeTime", dist.method = "bray", abundance.weighted = TRUE, output.rand = TRUE, SES = TRUE)
t1$res_NST$index.grp

# test the NST difference between each pair of groups
t1$cal_NST_test(method = "nst.boot")

# convert long format table to square matrix
# the 10th column: MST.ij.bray in t1$res_NST$index.pair
test <- t1$cal_NST_convert(10)

# for pNST method, phylogenetic tree is needed
t1$cal_NST(method = "pNST", group = "Group", output.rand = TRUE, SES = TRUE)
t1$cal_NST_test(method = "nst.boot")

str(t1)

t1$cal_NRI(null.model = "taxa.labels", abundance.weighted = FALSE, runs = 999)
t1$cal_NTI(null.model = "taxa.labels", abundance.weighted = TRUE, runs = 999)



```



